# CoocVectorizer

In [1]:
import numpy as np
import math, joblib
from deepART import base, nlp

/usr/local/lib/python3.7/site-packages/gensim/similarities/__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


## Without Filter

### fit

In [2]:
trial_sents = ['Hello I love you I hate you'.split(), 'You are a piece of shit and a god'.split(), 'Facebook is life I am god'.split(),
               'I love you so much I gonna die'.split(), 'I love god and hate Facebook'.split()]
trial_vectorizer = nlp.cooc_vec.CoocVectorizer()
trial_vectorizer.fit(trial_sents)

Fitting of Vectorizer Starts...

Building Vocab-Index Dictionary...
Number of Distinct Words:  20 


Swapping Words with Their Respective Indices...


Done...


Building Co-Occurence Matrix...
Converting All Matrix Entries to Mutual Information Estimates...
Done...

Normalizing Matrix...
Done...

Done...



/usr/local/lib/python3.7/site-packages/deepART/nlp/cooc_vec/cooccurrence.py:224: RuntimeWarning: invalid value encountered in double_scalars
  computed = P_X_GIVEN_Y / P_X


In [3]:
trial_vectorizer.counts_matrix

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 4., 0., 2., 1., 0., 0.,
        0., 2., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 2., 0., 1., 0., 0., 1.,
        0., 1., 2., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1.,
        1., 0., 0., 0.],
       [0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0.],
       [1., 0., 4., 2., 1., 0.

In [4]:
trial_vectorizer.matrix

array([[0.        , 0.        , 0.        , 0.        , 0.60382138,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.32296527, 0.7287614 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.45694698, 0.54859154, 0.54859154,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.43507943, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.42798595,
        0.4647404 , 0.        , 0.35648907, 0.        , 0.        ,
        0.22891637, 0.        , 0.37618346, 0.42798595, 0.        ,
        0.        , 0.        , 0.31092004, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.41194909, 0.        , 0.        ,
        0.26452954, 0.        , 0.43470739, 0

In [5]:
trial_vectorizer.vocabulary

{'gonna': 0,
 'shit': 1,
 'you': 2,
 'god': 3,
 'much': 4,
 'are': 5,
 'life': 6,
 'a': 7,
 'piece': 8,
 'of': 9,
 'i': 10,
 'die': 11,
 'hate': 12,
 'so': 13,
 'facebook': 14,
 'am': 15,
 'is': 16,
 'love': 17,
 'and': 18,
 'hello': 19}

In [6]:
trial_vectorizer.transform(['I love you god'.split()])

Building Vocab-Index Dictionary...
Number of Distinct Words:  4 


Swapping Words with Their Respective Indices...


Done...


Extracting Cooccurrence Vectors...

Done...



[[array([0.31568816, 0.        , 0.19537851, 0.23056683, 0.29072165,
         0.        , 0.29072165, 0.        , 0.        , 0.        ,
         0.        , 0.35087648, 0.25553334, 0.29072165, 0.        ,
         0.31568816, 0.31568816, 0.2112013 , 0.        , 0.35087648]),
  array([0.        , 0.        , 0.31849685, 0.37585918, 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.25348546, 0.        , 0.        , 0.47392074, 0.        ,
         0.        , 0.        , 0.        , 0.37585918, 0.57198231]),
  array([0.        , 0.        , 0.        , 0.        , 0.42798595,
         0.4647404 , 0.        , 0.35648907, 0.        , 0.        ,
         0.22891637, 0.        , 0.37618346, 0.42798595, 0.        ,
         0.        , 0.        , 0.31092004, 0.        , 0.        ]),
  array([0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.41194909, 0.        , 0.        ,
         0.26452954, 0.     

In [7]:
print('i: {}\n'.format(trial_vectorizer.matrix[trial_vectorizer.vocabulary['i'], :]))
print('love: {}\n'.format(trial_vectorizer.matrix[trial_vectorizer.vocabulary['love'], :]))
print('you: {}\n'.format(trial_vectorizer.matrix[trial_vectorizer.vocabulary['you'], :]))
print('god: {}\n'.format(trial_vectorizer.matrix[trial_vectorizer.vocabulary['god'], :]))

i: [0.31568816 0.         0.19537851 0.23056683 0.29072165 0.
 0.29072165 0.         0.         0.         0.         0.35087648
 0.25553334 0.29072165 0.         0.31568816 0.31568816 0.2112013
 0.         0.35087648]

love: [0.         0.         0.31849685 0.37585918 0.         0.
 0.         0.         0.         0.         0.25348546 0.
 0.         0.47392074 0.         0.         0.         0.
 0.37585918 0.57198231]

you: [0.         0.         0.         0.         0.42798595 0.4647404
 0.         0.35648907 0.         0.         0.22891637 0.
 0.37618346 0.42798595 0.         0.         0.         0.31092004
 0.         0.        ]

god: [0.         0.         0.         0.         0.         0.
 0.         0.41194909 0.         0.         0.26452954 0.
 0.43470739 0.         0.         0.53704139 0.         0.35929076
 0.39223495 0.        ]



### fit_transform

In [8]:
trial_sents = ['Hello I love you I hate you'.split(), 'You are a piece of shit and a god'.split(), 'Facebook is life I am god'.split(),
               'I love you so much I gonna die'.split(), 'I love god and hate Facebook'.split()]
trial_vectorizer_1 = nlp.cooc_vec.CoocVectorizer()
trial_vectorizer_1.fit_transform(trial_sents)

Building Vocab-Index Dictionary...
Number of Distinct Words:  20 


Swapping Words with Their Respective Indices...


Done...


Building Co-Occurence Matrix...
Converting All Matrix Entries to Mutual Information Estimates...
Done...

Normalizing Matrix...
Done...

Extracting Cooccurrence Vectors...

Done...



[[array([0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.59289246, 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.80528165, 0.        , 0.        ]),
  array([0.31568816, 0.        , 0.19537851, 0.23056683, 0.29072165,
         0.        , 0.29072165, 0.        , 0.        , 0.        ,
         0.        , 0.35087648, 0.25553334, 0.29072165, 0.        ,
         0.31568816, 0.31568816, 0.2112013 , 0.        , 0.35087648]),
  array([0.        , 0.        , 0.31849685, 0.37585918, 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.25348546, 0.        , 0.        , 0.47392074, 0.        ,
         0.        , 0.        , 0.        , 0.37585918, 0.57198231]),
  array([0.        , 0.        , 0.        , 0.        , 0.42798595,
         0.4647404 , 0.        , 0.35648907, 0.        , 0.        ,
         0.22891637, 0.     

### Streaming, incremental fitting

In [9]:
trial_sents = ['Hello I love you I hate you'.split(), 'You are a piece of shit and a god'.split(), 'Facebook is life I am god'.split(),
               'I love you so much I gonna die'.split(), 'I love god and hate Facebook'.split()]
trial_vectorizer_2 = nlp.cooc_vec.CoocVectorizer()
trial_vectorizer_2.fit(trial_sents)

Fitting of Vectorizer Starts...

Building Vocab-Index Dictionary...
Number of Distinct Words:  20 


Swapping Words with Their Respective Indices...


Done...


Building Co-Occurence Matrix...
Converting All Matrix Entries to Mutual Information Estimates...
Done...

Normalizing Matrix...
Done...

Done...



In [10]:
trial_vectorizer_2.vocabulary

{'gonna': 0,
 'shit': 1,
 'you': 2,
 'god': 3,
 'much': 4,
 'are': 5,
 'life': 6,
 'a': 7,
 'piece': 8,
 'of': 9,
 'i': 10,
 'die': 11,
 'hate': 12,
 'so': 13,
 'facebook': 14,
 'am': 15,
 'is': 16,
 'love': 17,
 'and': 18,
 'hello': 19}

In [11]:
print(trial_vectorizer_2.matrix.shape, trial_vectorizer_2.counts_matrix.shape)

(20, 20) (20, 20)


In [12]:
trial_vectorizer_2.fit(['She has curves'.split()]) # 3 new words

Fitting of Vectorizer Starts...

Updating Vocabulary With New Words...
Done...

Swapping Words with Their Respective Indices...


Done...


Updating Cooccurrence Matrix...

Building Co-Occurence Matrix...
Done...

Converting All Matrix Entries to Mutual Information Estimates...
Done...

Normalizing Matrix...
Done...

Done...



In [13]:
trial_vectorizer_2.vocabulary

{'gonna': 0,
 'shit': 1,
 'you': 2,
 'god': 3,
 'much': 4,
 'are': 5,
 'life': 6,
 'a': 7,
 'piece': 8,
 'of': 9,
 'i': 10,
 'die': 11,
 'hate': 12,
 'so': 13,
 'facebook': 14,
 'am': 15,
 'is': 16,
 'love': 17,
 'and': 18,
 'hello': 19,
 'she': 20,
 'curves': 21,
 'has': 22}

In [14]:
print(trial_vectorizer_2.matrix.shape, trial_vectorizer_2.counts_matrix.shape)

(23, 23) (23, 23)


## With Filter

### fit

In [15]:
trial_sents = ['Hello I I love love you you I I hate hate you you'.split(), 'You You are are a a piece piece of of shit shit and and a a god god'.split(), 'Facebook Facebook is is life life I I am am god god'.split(), 'I I love love you you so so much much I I gonna gonna die die'.split()]
trial_vectorizer_3 = nlp.cooc_vec.CoocVectorizer(min_df=2, max_df=4, cooc_likelihood=False, normalize=None) #counts only
trial_vectorizer_3.fit(trial_sents)

Fitting of Vectorizer Starts...

Building A Dictionary of Occurrences for Rejected Words for Storage...

Swapping Words with Their Respective Indices...


Done...


Building Co-Occurence Matrix...
Done...



In [16]:
trial_vectorizer_3.vocabulary

{'love': 0,
 'hate': 1,
 'are': 2,
 'a': 3,
 'piece': 4,
 'of': 5,
 'shit': 6,
 'and': 7,
 'god': 8,
 'facebook': 9,
 'is': 10,
 'life': 11,
 'am': 12,
 'so': 13,
 'much': 14,
 'gonna': 15,
 'die': 16}

In [17]:
trial_vectorizer_3.word_counts

{'hello': 1,
 'i': 10,
 'love': 4,
 'you': 8,
 'hate': 2,
 'are': 2,
 'a': 4,
 'piece': 2,
 'of': 2,
 'shit': 2,
 'and': 2,
 'god': 4,
 'facebook': 2,
 'is': 2,
 'life': 2,
 'am': 2,
 'so': 2,
 'much': 2,
 'gonna': 2,
 'die': 2}

In [18]:
print('Rejected Words Are {}'.format(trial_vectorizer_3.rejected_words.keys()))

Rejected Words Are dict_keys(['hello', 'i', 'you'])


In [19]:
print(trial_vectorizer_3.counts_matrix.shape, trial_vectorizer_3.matrix.shape)

(17, 17) (17, 17)


In [20]:
trial_vectorizer_3.transform(['Facebook is life'.split()])

Building Vocab-Index Dictionary...
Number of Distinct Words:  3 


Swapping Words with Their Respective Indices...


Done...


Extracting Cooccurrence Vectors...

Done...



[[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 3., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 3., 0., 3., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 3., 0., 0., 0., 0., 0., 0.])]]

In [21]:
print('facebook: {}\n'.format(trial_vectorizer_3.matrix[trial_vectorizer_3.vocabulary['facebook'], :]))
print('is: {}\n'.format(trial_vectorizer_3.matrix[trial_vectorizer_3.vocabulary['is'], :]))
print('life: {}\n'.format(trial_vectorizer_3.matrix[trial_vectorizer_3.vocabulary['life'], :]))

facebook: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0.]

is: [0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 0. 3. 0. 0. 0. 0. 0.]

life: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0.]



### fit_transform

In [22]:
trial_sents = ['Hello I I love love you you I I hate hate you you'.split(), 'You You are are a a piece piece of of shit shit and and a a god god'.split(), 'Facebook Facebook is is life life I I am am god god'.split(), 'I I love love you you so so much much I I gonna gonna die die'.split()]
trial_vectorizer_3 = nlp.cooc_vec.CoocVectorizer(min_df=2, max_df=4, cooc_likelihood=False, normalize=None) #counts only
trial_vectorizer_3.fit_transform(trial_sents)

Building A Dictionary of Occurrences for Rejected Words for Storage...

Swapping Words with Their Respective Indices...


Done...


Building Co-Occurence Matrix...
Extracting Cooccurrence Vectors...

Done...



[[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [23]:
trial_vectorizer_3.vocabulary

{'love': 0,
 'hate': 1,
 'are': 2,
 'a': 3,
 'piece': 4,
 'of': 5,
 'shit': 6,
 'and': 7,
 'god': 8,
 'facebook': 9,
 'is': 10,
 'life': 11,
 'am': 12,
 'so': 13,
 'much': 14,
 'gonna': 15,
 'die': 16}

In [24]:
trial_vectorizer_3.word_counts

{'hello': 1,
 'i': 10,
 'love': 4,
 'you': 8,
 'hate': 2,
 'are': 2,
 'a': 4,
 'piece': 2,
 'of': 2,
 'shit': 2,
 'and': 2,
 'god': 4,
 'facebook': 2,
 'is': 2,
 'life': 2,
 'am': 2,
 'so': 2,
 'much': 2,
 'gonna': 2,
 'die': 2}

### Streaming, incremental fitting (new words (not in current vocabulary) which are accepted)

In [25]:
trial_sents = ['Hello I I love love you you I I hate hate you you'.split(), 'You You are are a a piece piece of of shit shit and and a a god god'.split(),
               'Facebook Facebook is is life life I I am am god god'.split(), 'I I love love you you so so much much I I gonna gonna die die'.split(),
              'I I love love god god and and hate hate Facebook Facebook'.split()]
trial_vectorizer_4 = nlp.cooc_vec.CoocVectorizer(min_df=2, max_df=4, cooc_likelihood=False, normalize=None) #counts only
trial_vectorizer_4.fit(trial_sents)

Fitting of Vectorizer Starts...

Building A Dictionary of Occurrences for Rejected Words for Storage...

Swapping Words with Their Respective Indices...


Done...


Building Co-Occurence Matrix...
Done...



In [26]:
trial_vectorizer_4.word_counts

{'hello': 1,
 'i': 12,
 'love': 6,
 'you': 8,
 'hate': 4,
 'are': 2,
 'a': 4,
 'piece': 2,
 'of': 2,
 'shit': 2,
 'and': 4,
 'god': 6,
 'facebook': 4,
 'is': 2,
 'life': 2,
 'am': 2,
 'so': 2,
 'much': 2,
 'gonna': 2,
 'die': 2}

In [27]:
trial_vectorizer_4.rejected_words.keys()

dict_keys(['hello', 'i', 'love', 'you', 'god'])

In [28]:
trial_vectorizer_4.vocabulary_size

15

In [29]:
trial_vectorizer_4.fit(['She she has has curves curves'.split()]) # 3 new words accepted because counts in range

Fitting of Vectorizer Starts...

Building A Dictionary of Occurrences for Rejected Words for Storage...

Swapping Words with Their Respective Indices...


Done...


Updating Cooccurrence Matrix...

Building Co-Occurence Matrix...
Done...

Done...



In [30]:
trial_vectorizer_4.vocabulary_size

18

### Streaming, incremental fitting (words (in current vocabulary) which are rejected previously but accepted in this run)

In [31]:
trial_sents = ['Hello I I love love you you I I hate hate you you'.split(), 'You You are are a a piece piece of of shit shit and and a a god god'.split(),
               'Facebook Facebook is is life life I I am am god god'.split(), 'I I love love you you so so much much I I gonna gonna die die'.split(),
              'I I love love god god and and hate hate Facebook Facebook'.split()]
trial_vectorizer_5 = nlp.cooc_vec.CoocVectorizer(min_df=2, max_df=4, cooc_likelihood=False, normalize=None) #counts only
trial_vectorizer_5.fit(trial_sents)

Fitting of Vectorizer Starts...

Building A Dictionary of Occurrences for Rejected Words for Storage...

Swapping Words with Their Respective Indices...


Done...


Building Co-Occurence Matrix...
Done...



In [32]:
trial_vectorizer_5.rejected_words.keys()

dict_keys(['hello', 'i', 'love', 'you', 'god'])

In [33]:
trial_vectorizer_5.word_counts

{'hello': 1,
 'i': 12,
 'love': 6,
 'you': 8,
 'hate': 4,
 'are': 2,
 'a': 4,
 'piece': 2,
 'of': 2,
 'shit': 2,
 'and': 4,
 'god': 6,
 'facebook': 4,
 'is': 2,
 'life': 2,
 'am': 2,
 'so': 2,
 'much': 2,
 'gonna': 2,
 'die': 2}

In [34]:
trial_vectorizer_5.vocabulary

{'hate': 0,
 'are': 1,
 'a': 2,
 'piece': 3,
 'of': 4,
 'shit': 5,
 'and': 6,
 'facebook': 7,
 'is': 8,
 'life': 9,
 'am': 10,
 'so': 11,
 'much': 12,
 'gonna': 13,
 'die': 14}

In [35]:
trial_vectorizer_5.vocabulary_size

15

In [36]:
trial_vectorizer_5.fit(['Hello I love you'.split()]) # only hello is accepted 

Fitting of Vectorizer Starts...

Building A Dictionary of Occurrences for Rejected Words for Storage...

Swapping Words with Their Respective Indices...


Done...


Updating Cooccurrence Matrix...

Building Co-Occurence Matrix...
Done...

Done...



In [37]:
trial_vectorizer_5.vocabulary_size

16

In [38]:
trial_vectorizer_5.word_counts

{'hello': 2,
 'i': 13,
 'love': 7,
 'you': 9,
 'hate': 4,
 'are': 2,
 'a': 4,
 'piece': 2,
 'of': 2,
 'shit': 2,
 'and': 4,
 'god': 6,
 'facebook': 4,
 'is': 2,
 'life': 2,
 'am': 2,
 'so': 2,
 'much': 2,
 'gonna': 2,
 'die': 2}

In [39]:
trial_vectorizer_5.rejected_words.keys()

dict_keys(['i', 'love', 'you', 'god'])

### Streaming, incremental fitting (words (in current vocabulary) which are not rejected previously but rejected in this run)

In [40]:
trial_sents = ['Hello I I love love you you I I hate hate you you'.split(), 'You You are are a a piece piece of of shit shit and and a a god god'.split(),
               'Facebook Facebook is is life life I I am am god god'.split(), 'I I love love you you so so much much I I gonna gonna die die'.split(),
              'I I love love god god and and hate hate Facebook Facebook'.split()]
trial_vectorizer_6 = nlp.cooc_vec.CoocVectorizer(min_df=2, max_df=4, cooc_likelihood=False, normalize=None) #counts only
trial_vectorizer_6.fit(trial_sents)

Fitting of Vectorizer Starts...

Building A Dictionary of Occurrences for Rejected Words for Storage...

Swapping Words with Their Respective Indices...


Done...


Building Co-Occurence Matrix...
Done...



In [41]:
trial_vectorizer_5.rejected_words.keys()

dict_keys(['i', 'love', 'you', 'god'])

In [42]:
trial_vectorizer_5.word_counts

{'hello': 2,
 'i': 13,
 'love': 7,
 'you': 9,
 'hate': 4,
 'are': 2,
 'a': 4,
 'piece': 2,
 'of': 2,
 'shit': 2,
 'and': 4,
 'god': 6,
 'facebook': 4,
 'is': 2,
 'life': 2,
 'am': 2,
 'so': 2,
 'much': 2,
 'gonna': 2,
 'die': 2}

In [43]:
trial_vectorizer_5.vocabulary

{'hate': 0,
 'are': 1,
 'a': 2,
 'piece': 3,
 'of': 4,
 'shit': 5,
 'and': 6,
 'facebook': 7,
 'is': 8,
 'life': 9,
 'am': 10,
 'so': 11,
 'much': 12,
 'gonna': 13,
 'die': 14,
 'hello': 15}

In [44]:
trial_vectorizer_6.fit(['I hate Facebook'.split()]) # hate and facebook are rejected

Fitting of Vectorizer Starts...

Building A Dictionary of Occurrences for Rejected Words for Storage...

Swapping Words with Their Respective Indices...


Done...


Updating Cooccurrence Matrix...

Building Co-Occurence Matrix...
Done...

Done...



## Save Vectorizer

In [45]:
trial_vectorizer_4.save('trial.p')

## Load Vectorizer

In [46]:
trial_vectorizer2 = base.load_model('trial.p')